package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "turn_off_rgb_lights",
    deps = [
        "//code/utilities/program/call:lib",
    ],
)