package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")

hcp(
    name = "sound",
    deps = [
    ],
)

hcp(
    name = "sounds",
    deps = [
        "//code/programs/games/mario/sound",
    ],
)

hcp(
    name = "sounds_loader",
    deps = [
        "//code/programs/games/mario/sound:sounds",
    ],
)
