package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

cc_library(
    name = "function_profiler",
    srcs = ["function_profiler.cpp"],
    hdrs = ["function_profiler.hpp"],
    deps = [
    ],
)